name: Continuous Deployment

on:
  push:
    branches:
      - main
      
env:
  PROJECT_ID: challenge-app-ml
  SERVICE: challenge-app-ml
  REGION: us-central1
  DOCKER_HUB_REPOSITORY: marcochacon/challenge-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Google Auth
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Docker Hub Auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |-
          docker build -t "${{ env.DOCKER_HUB_REPOSITORY }}:commit-${{ env.IMAGE_TAG }}" ./
          docker push "${{ env.DOCKER_HUB_REPOSITORY }}:commit-${{ env.IMAGE_TAG }}"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --image docker.io/${{ env.DOCKER_HUB_REPOSITORY }}:commit-${{ env.IMAGE_TAG }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --project ${{ env.PROJECT_ID }}
            
      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
