name: Continuous Deployment

on:
  push:
    branches:
      - main
      
env:
  PROJECT_ID: challenge-app-ml
  SERVICE: challenge-app-ml
  REGION: us-central1
  DOCKER_HUB_REPOSITORY: marcochacon/challenge-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Google Auth
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Docker Hub Auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |-
          docker build -t "${{ env.DOCKER_HUB_REPOSITORY }}:commit-${{ env.IMAGE_TAG }}" ./
          docker push "${{ env.DOCKER_HUB_REPOSITORY }}:commit-${{ env.IMAGE_TAG }}"


      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy challenge-app-ml \
            --image docker.io/marcochacon/challenge-app::commit-${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}
