name: Continuous Integration

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - "README.md"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Lint with Black
        run: |
          pip install black
          black . --check

      - name: Test with pytest
        run: |
          pytest tests/
